ARG WP_VERSION
ARG PHP_VERSION
ARG DOCKER_REGISTRY

FROM ${DOCKER_REGISTRY:-}wp-graphql-testing:latest-wp${WP_VERSION}-php${PHP_VERSION}

# Move the base image app setup script out of the way
# Put our shell script in place which will invoke the base image script
RUN cp /usr/local/bin/app-setup.sh /usr/local/bin/original-app-setup.sh
COPY docker/app.setup.sh /usr/local/bin/app-setup.sh

ENV PROJECT_DIR="${PLUGINS_DIR}/wp-graphql-smart-cache"

RUN echo "pcov.directory = /var/www/html/wp-content/plugins/wp-graphql-smart-cache" >> /usr/local/etc/php/conf.d/docker-php-ext-pcov.ini

# Own the test runner so the inherited unconditional Composer update cannot run.
COPY docker/testing-entrypoint.sh /usr/local/bin/testing-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/testing-entrypoint.sh"]
